export const FETCH_RESULTS = 'fetch_results'
export const TRAIN_CLASSIFIER = 'train_classifier'
export const APPLY_MODE = 'apply_mode'
export const CLASSIFY_RESULTS = 'classify_results'
export const DISPLAY_CATEGORY = 'display_category'
export const DISABLE_TRAIN_BUTTON = 'disable_train_button'
